seed: 1
model: 'space'
exp_name: bowling_v7
resume: false

resume_ckpt: '../output/checkpoints/bowling_v7/best_precision_relevant.pth'

parallel: true
device_ids: [0]
device: 'cuda:0'

logdir: '../output/logs/'
checkpointdir: '../output/checkpoints/'
latentsdir: '../output/latents/'


dataset: 'ATARI'
dataset_style: ''
dataset_roots:
  OBJ3D_SMALL: '../data/OBJ3D_SMALL'
  OBJ3D_LARGE: '../data/OBJ3D_LARGE'
  ATARI: '../aiml_atari_data'


train:
  log: true
  batch_size: 2
  max_epochs: 10000
  max_steps: 40000
  print_every: 100
  save_every: 100
  num_workers: 8
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: true
  eval_every: 500
  solver:
    fg:
      optim: 'RMSprop'
      lr: 3e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

moc_cfg:
  motion_input: false
  motion: true
  motion_kind: 'mode'

space_cfg:
  G: 16  # Increased grid resolution for finer object localization

  z_scale_mean_start_value: -0.5  # Lower value to encourage smaller object detection
  z_scale_mean_end_value: -2.0  # Keep scale small throughout training

  fix_alpha_steps: 15000  # More steps to allow stabilization  
  fix_alpha_value: 0.01  # Lower alpha to allow adaptive learning  


eval:
  checkpoint: 'last'
  metric: ap_avg

gamelist: [
  'ALE/Bowling-v5'
]
