seed: 1
model: 'space'
exp_name: pong
resume: false
save_relevant_objects: false

resume_ckpt: ../output/checkpoints/pong/model_000004401.pth
parallel: false
device_ids: [0]
device: 'cpu'

logdir: '../output/logs/'
checkpointdir: '../output/checkpoints/'
latentsdir: '../output/latents/'

dataset: 'ATARI'
dataset_style: ''
dataset_roots:
  OBJ3D_SMALL: '../data/OBJ3D_SMALL'
  OBJ3D_LARGE: '../data/OBJ3D_LARGE'
  ATARI: '../aiml_atari_data'

train:
  log: true
  batch_size: 1 #was 16
  max_epochs: 10000
  max_steps: 5000
  print_every: 100
  save_every: 100
  num_workers: 0
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: false
  eval_every: 10
  log_latents: false
  solver:
    fg:
      optim: 'RMSprop'
      lr: 3e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

moc_cfg:
  motion_input: false
  motion: true
  motion_kind: 'mode'

  motion_underestimating: 1.5

space_cfg:
  G: 16

  fix_alpha_steps: -1
  fix_alpha_value: 0.1


# For engine.eval
eval:
  checkpoint: 'last'
  eval_ckpt: '../output/checkpoints/pong/model_000004401.pth' # to manually specify the eval checkpoint
  metric: ap_avg

gamelist: [
    'ALE/Pong-v5',
    ]
